#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(HERE, "..");
const SOURCE_PATH = path.join(PACKAGE_ROOT, "src", "tokens", "tokens.json");
const DIST_DIR = path.join(PACKAGE_ROOT, "dist");
const CHECK_ONLY = process.argv.includes("--check");

const tokens = JSON.parse(fs.readFileSync(SOURCE_PATH, "utf8"));
const CANONICAL_PRIMARY = "#4628CC";

if (tokens.meta?.canonicalPrimary !== CANONICAL_PRIMARY) {
  throw new Error(
    "tokens.json must declare the canonical Fabric primary " +
      CANONICAL_PRIMARY,
  );
}
if (tokens.color?.primary?.["600"] !== CANONICAL_PRIMARY) {
  throw new Error(
    "color.primary.600 must equal the canonical Fabric primary " +
      CANONICAL_PRIMARY,
  );
}

function kebab(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .toLowerCase();
}

function cssVariable(parts) {
  return "--fabric-ds-" + parts.map(kebab).join("-");
}

function flatten(object, prefix = []) {
  const values = [];
  for (const [key, value] of Object.entries(object)) {
    const next = [...prefix, key];
    if (value && typeof value === "object" && !Array.isArray(value)) {
      values.push(...flatten(value, next));
    } else {
      values.push([next, value]);
    }
  }
  return values;
}

function referenceToCss(value) {
  if (typeof value !== "string") return String(value);
  const match = value.match(/^\{([^}]+)\}$/);
  if (!match) return value;
  return "var(" + cssVariable(match[1].split(".")) + ")";
}

function tokenAt(reference) {
  return reference
    .replace(/^\{|\}$/g, "")
    .split(".")
    .reduce((value, key) => value?.[key], tokens);
}

function resolveValue(value) {
  let resolved = value;
  const seen = new Set();
  while (typeof resolved === "string" && /^\{[^}]+\}$/.test(resolved)) {
    if (seen.has(resolved)) {
      throw new Error("Circular token reference: " + resolved);
    }
    seen.add(resolved);
    resolved = tokenAt(resolved);
  }
  if (resolved === undefined) {
    throw new Error("Unknown token reference: " + value);
  }
  return resolved;
}

function resolveSemanticThemes() {
  return Object.fromEntries(
    Object.entries(tokens.semantic).map(([appearance, values]) => [
      appearance,
      Object.fromEntries(
        Object.entries(values).map(([name, value]) => [
          name,
          resolveValue(value),
        ]),
      ),
    ]),
  );
}

function cssDeclarations(object, prefix, semantic = false) {
  return flatten(object).map(([parts, value]) => {
    const variableParts = semantic ? ["semantic", ...parts] : [...prefix, ...parts];
    return "  " + cssVariable(variableParts) + ": " + referenceToCss(value) + ";";
  });
}

function buildCss() {
  const root = [
    ...cssDeclarations(tokens.color, ["color"]),
    "  --fabric-ds-brand-primary: var(--fabric-ds-color-primary-600);",
    ...cssDeclarations(tokens.typography, ["typography"]),
    ...cssDeclarations(tokens.spacing, ["spacing"]),
    ...cssDeclarations(tokens.radius, ["radius"]),
    ...cssDeclarations(tokens.controlHeight, ["control-height"]),
    ...cssDeclarations(tokens.density, ["density"]),
    ...cssDeclarations(tokens.motion, ["motion"]),
    ...cssDeclarations(tokens.semantic.light, [], true),
  ];
  const dark = cssDeclarations(tokens.semantic.dark, [], true);

  return [
    "/* Generated by apps/design-system/scripts/generate-tokens.mjs. */",
    "/* Do not edit this file directly; edit src/tokens/tokens.json. */",
    "",
    ":root {",
    ...root,
    "}",
    "",
    "[data-fabric-color-scheme='dark'],",
    ".fabric-theme-dark {",
    ...dark,
    "}",
    "",
    "@media (prefers-reduced-motion: reduce) {",
    "  :root {",
    "    --fabric-ds-motion-duration-instant: 1ms;",
    "    --fabric-ds-motion-duration-fast: 1ms;",
    "    --fabric-ds-motion-duration-base: 1ms;",
    "    --fabric-ds-motion-duration-slow: 1ms;",
    "    --fabric-ds-motion-duration-emphasis: 1ms;",
    "  }",
    "}",
    "",
  ].join("\n");
}

function buildJavaScript() {
  return [
    "/* Generated by apps/design-system/scripts/generate-tokens.mjs. */",
    "export const FABRIC_PRIMARY = " +
      JSON.stringify(CANONICAL_PRIMARY) +
      ";",
    "export const colors = Object.freeze(" +
      JSON.stringify(tokens.color, null, 2) +
      ");",
    "export const semanticThemes = Object.freeze(" +
      JSON.stringify(tokens.semantic, null, 2) +
      ");",
    "export const resolvedSemanticThemes = Object.freeze(" +
      JSON.stringify(resolveSemanticThemes(), null, 2) +
      ");",
    "export const typography = Object.freeze(" +
      JSON.stringify(tokens.typography, null, 2) +
      ");",
    "export const spacing = Object.freeze(" +
      JSON.stringify(tokens.spacing, null, 2) +
      ");",
    "export const radius = Object.freeze(" +
      JSON.stringify(tokens.radius, null, 2) +
      ");",
    "export const controlHeight = Object.freeze(" +
      JSON.stringify(tokens.controlHeight, null, 2) +
      ");",
    "export const density = Object.freeze(" +
      JSON.stringify(tokens.density, null, 2) +
      ");",
    "export const motion = Object.freeze(" +
      JSON.stringify(tokens.motion, null, 2) +
      ");",
    "",
  ].join("\n");
}

function buildTypes() {
  return [
    "export declare const FABRIC_PRIMARY: \"#4628CC\";",
    "export declare const colors: Readonly<Record<string, Readonly<Record<string, string>>>>;",
    "export declare const semanticThemes: Readonly<Record<\"light\" | \"dark\", Readonly<Record<string, string>>>>;",
    "export declare const resolvedSemanticThemes: Readonly<Record<\"light\" | \"dark\", Readonly<Record<string, string>>>>;",
    "export declare const typography: Readonly<Record<string, unknown>>;",
    "export declare const spacing: Readonly<Record<string, string>>;",
    "export declare const radius: Readonly<Record<string, string>>;",
    "export declare const controlHeight: Readonly<Record<string, string>>;",
    "export declare const density: Readonly<Record<string, number>>;",
    "export declare const motion: Readonly<Record<string, unknown>>;",
    "",
  ].join("\n");
}

function buildTerminalTokens() {
  const light = tokens.semantic.light;
  const dark = tokens.semantic.dark;
  return (
    JSON.stringify(
      {
        schemaVersion: 1,
        brand: {
          primary: CANONICAL_PRIMARY,
          accent: tokens.color.primary["300"],
          muted: tokens.color.primary["100"],
        },
        light: {
          background: resolveValue(light.canvas),
          surface: resolveValue(light.surface),
          foreground: resolveValue(light.text),
          muted: resolveValue(light.textMuted),
          accent: resolveValue(light.action),
          success: resolveValue(light.success),
          warning: resolveValue(light.warning),
          danger: resolveValue(light.danger),
        },
        dark: {
          background: resolveValue(dark.canvas),
          surface: resolveValue(dark.surface),
          foreground: resolveValue(dark.text),
          muted: resolveValue(dark.textMuted),
          accent: resolveValue(dark.action),
          success: resolveValue(dark.success),
          warning: resolveValue(dark.warning),
          danger: resolveValue(dark.danger),
        },
      },
      null,
      2,
    ) + "\n"
  );
}

const outputs = new Map([
  [path.join(DIST_DIR, "tokens.css"), buildCss()],
  [path.join(DIST_DIR, "tokens.js"), buildJavaScript()],
  [path.join(DIST_DIR, "tokens.d.ts"), buildTypes()],
  [path.join(DIST_DIR, "tokens.terminal.json"), buildTerminalTokens()],
]);

let stale = false;
for (const [target, content] of outputs) {
  if (CHECK_ONLY) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
    if (current !== content) {
      stale = true;
      console.error(path.relative(PACKAGE_ROOT, target) + " is stale");
    }
    continue;
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content, "utf8");
  console.log("generated " + path.relative(PACKAGE_ROOT, target));
}

if (stale) process.exitCode = 1;
