"""Skill write-origin provenance for governed skill authoring.

The curator only consolidates/prunes skills it autonomously created via the
background self-improvement review fork. Skills a user asks a foreground
agent to write belong to the user and must never be auto-curated.

Background-review and explicit ``/learn`` turns author quarantined drafts;
the scheduled curator uses a distinct origin because its writes are protected
by a pre-run snapshot instead. The origin travels with pending records so
approval can preserve autonomous archive/ownership semantics without confusing
a user-owned learned skill with curator-managed sediment.

This module exposes a ContextVar that run_agent.py sets before each tool loop
so tool handlers (e.g. skill_manage create) can distinguish foreground,
background-review, explicit learning, follow-up quarantine, and curation.

The signal piggybacks on AIAgent._memory_write_origin, which is already
set to "background_review" for review-fork instances (see
_spawn_background_review in run_agent.py) and defaults to "assistant_tool"
for normal (foreground) agents.

Usage:
    from tools.skill_provenance import (
        set_current_write_origin,
        reset_current_write_origin,
        get_current_write_origin,
        is_autonomous_skill_writer,
    )

    token = set_current_write_origin("background_review")
    try:
        ...  # tool runs here
    finally:
        reset_current_write_origin(token)

    # inside a tool:
    if is_autonomous_skill_writer():
        mark_agent_created(skill_name)
"""

import contextvars
import re


_write_origin: contextvars.ContextVar[str] = contextvars.ContextVar(
    "skill_write_origin",
    default="foreground",
)

# Sentinel values for governed skill-authoring turns. The background-review
# value mirrors
# run_agent.py's AIAgent._memory_write_origin override in
# _spawn_background_review().
BACKGROUND_REVIEW = "background_review"
LEARN_REQUEST = "learn_request"
LEARN_FOLLOWUP = "learn_followup"
CURATOR = "curator"

# The marker is generated by ``agent.learn_prompt.build_learn_prompt`` on every
# supported surface.  It is deliberately recognizable (rather than secret): a
# user who types it manually only opts the turn into a *more restrictive*
# authoring sandbox.  Require a real token boundary so text such as
# ``[/learn]ing`` cannot accidentally change the turn's authority.
LEARN_MARKER = "[/learn]"
_LEARN_MARKER_RE = re.compile(r"^\s*\[/learn\](?:\s|$)")

# Skill writes from these origins are candidates, not active-library
# mutations.  Keep this policy next to the provenance values so callers do not
# grow subtly different origin lists.
QUARANTINED_SKILL_ORIGINS = frozenset(
    {BACKGROUND_REVIEW, LEARN_REQUEST, LEARN_FOLLOWUP}
)
AUTONOMOUS_SKILL_ORIGINS = frozenset({BACKGROUND_REVIEW, CURATOR})


def is_learn_request_message(user_message: object) -> bool:
    """Return whether *user_message* is the cross-surface ``/learn`` prompt.

    CLI, gateway, TUI, and desktop all execute the same prompt builder, so this
    one predicate is the authority boundary for every surface.  Matching is
    prefix-only and whitespace-tolerant; quoted or embedded marker text does
    not activate the policy.
    """
    return (
        isinstance(user_message, str)
        and _LEARN_MARKER_RE.match(user_message) is not None
    )


def origin_for_turn(configured_origin: str, user_message: object) -> str:
    """Resolve the write origin for one agent turn.

    ``/learn`` is implemented as a normal user turn whose prompt starts with a
    stable ``[/learn]`` marker.  Recognizing that marker here preserves the
    narrow waist: no new model tool, no tool-schema mutation, and no
    surface-specific state that could leak into later turns.  Binding happens
    again at the start of every turn. ``build_turn_context`` separately keeps
    the immediately following turn's skill writes quarantined as defense in
    depth against a model asking an unsupported prose clarification.

    A user can type the marker manually, but that only opts the turn into the
    safer quarantined-write path; it grants no additional capability.
    """
    origin = configured_origin or "foreground"
    if origin in AUTONOMOUS_SKILL_ORIGINS:
        return origin
    if is_learn_request_message(user_message):
        return LEARN_REQUEST
    return origin


def is_quarantined_skill_origin(origin: str | None = None) -> bool:
    """Return whether *origin* must write skill candidates to quarantine."""
    current = get_current_write_origin() if origin is None else origin
    return current in QUARANTINED_SKILL_ORIGINS


def set_current_write_origin(origin: str) -> contextvars.Token[str]:
    """Bind the active write origin to the current context.

    Returns a Token the caller must pass to reset_current_write_origin
    in a finally block.
    """
    return _write_origin.set(origin or "foreground")


def reset_current_write_origin(token: contextvars.Token[str]) -> None:
    """Restore the prior write origin context."""
    _write_origin.reset(token)


def get_current_write_origin() -> str:
    """Return the active write origin.

    Default: "foreground" — any tool call made by a regular (non-review)
    agent, from the CLI, the gateway, cron, or a subagent.

    "background_review" — the self-improvement review fork; only skills
    created under this origin should be marked agent-created for curator
    management.

    "learn_request" — a user-initiated ``/learn`` turn. Skill writes from this
    origin are quarantined until explicit approval, but remain user-owned
    after promotion.

    "learn_followup" — the immediately following turn. Its normal tool surface
    is restored, but skill writes remain quarantined so a prose continuation
    cannot silently mutate the active library.

    "curator" — the scheduled snapshot-governed curator. It shares autonomous
    ownership guards but applies its coordinated mutations directly.
    """
    return _write_origin.get()


def is_background_review() -> bool:
    """Convenience: True iff the current write origin is the background
    review fork."""
    return get_current_write_origin() == BACKGROUND_REVIEW


def is_curator() -> bool:
    """Return whether the snapshot-governed curator owns this tool call."""
    return get_current_write_origin() == CURATOR


def is_autonomous_skill_writer() -> bool:
    """Return whether an autonomous Fabric actor owns this tool call.

    Background self-improvement and scheduled curation share ownership,
    read-before-write, and protected-skill guards.  Their lifecycle differs:
    background review always creates drafts, while the curator mutates the
    snapshot-protected active tree directly.  Keeping that distinction in the
    origin prevents the two policies from being accidentally coupled again.
    """
    return get_current_write_origin() in AUTONOMOUS_SKILL_ORIGINS
