"""Tests for scripts/commit_identity_audit.py (commit-identity guardrails)."""

from __future__ import annotations

import importlib.util
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "commit_identity_audit.py"
CANONICAL_NAME = "PrimeOdin"
CANONICAL_EMAIL = "11676741+ObliviousOdin@users.noreply.github.com"


def _load_module():
    spec = importlib.util.spec_from_file_location("commit_identity_audit", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class MessageAuditTests(unittest.TestCase):
    """Unit tests for the message-body rules."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.audit = _load_module()

    def test_clean_conventional_message_passes(self) -> None:
        message = "feat(core): add a thing\n\nLonger body explaining why.\n"
        self.assertEqual(self.audit.audit_message(message), [])

    def test_ai_coauthor_trailer_fails(self) -> None:
        for identity in (
            "Claude <noreply@anthropic.com>",
            "Claude Opus 4.8 <noreply@anthropic.com>",
            "OpenAI Codex <noreply@openai.com>",
            "Copilot <copilot@github.com>",
        ):
            message = f"fix: x\n\nCo-Authored-By: {identity}\n"
            with self.subTest(identity=identity):
                self.assertTrue(self.audit.audit_message(message))

    def test_non_allowlisted_human_coauthor_fails_closed(self) -> None:
        message = "fix: x\n\nCo-authored-by: Random Person <random@example.com>\n"
        self.assertTrue(self.audit.audit_message(message))

    def test_canonical_and_dependabot_coauthors_pass(self) -> None:
        message = (
            "fix: x\n\n"
            f"Co-authored-by: {CANONICAL_NAME} <{CANONICAL_EMAIL}>\n"
            "Co-authored-by: dependabot[bot] "
            "<49699333+dependabot[bot]@users.noreply.github.com>\n"
        )
        self.assertEqual(self.audit.audit_message(message), [])

    def test_generated_with_footer_fails(self) -> None:
        for line in (
            "Generated with [Claude Code](https://claude.com/claude-code)",
            "\U0001f916 Generated with tooling",
            "generated by an assistant",
        ):
            with self.subTest(line=line):
                self.assertTrue(self.audit.audit_message(f"fix: x\n\n{line}\n"))

    def test_session_links_fail(self) -> None:
        for line in (
            "Claude-Session: https://claude.ai/code/session_abc",
            "See https://chatgpt.com/share/xyz",
        ):
            with self.subTest(line=line):
                self.assertTrue(self.audit.audit_message(f"fix: x\n\n{line}\n"))

    def test_prose_mention_of_tool_names_is_allowed(self) -> None:
        # Real main commit e82061f mentions Claude Code in the subject; prose
        # mentions are fine — only structured attribution is forbidden.
        message = (
            "refactor(auth): stop impersonating Claude Code for native "
            "Anthropic requests\n\nExplains the change in prose.\n"
        )
        self.assertEqual(self.audit.audit_message(message), [])


class RepoAuditTests(unittest.TestCase):
    """End-to-end tests against throwaway git repositories."""

    def setUp(self) -> None:
        self.tempdir = tempfile.TemporaryDirectory()
        self.root = Path(self.tempdir.name)
        self.repo = self.root / "repo"
        self.repo.mkdir()
        self.env = {
            **os.environ,
            "GIT_CONFIG_GLOBAL": str(self.root / "gitconfig"),
            "GIT_CONFIG_NOSYSTEM": "1",
            "HOME": str(self.root),
        }
        self._git("init", "-q", "-b", "main")

    def tearDown(self) -> None:
        self.tempdir.cleanup()

    def _git(self, *args: str) -> None:
        subprocess.run(
            ["git", *args], cwd=self.repo, check=True, env=self.env,
            capture_output=True,
        )

    def _commit(self, message: str, *, name: str, email: str) -> None:
        (self.repo / "file.txt").open("a", encoding="utf-8").close()
        with (self.repo / "file.txt").open("a", encoding="utf-8") as handle:
            handle.write("x\n")
        self._git("add", "file.txt")
        identity = {
            **self.env,
            "GIT_AUTHOR_NAME": name,
            "GIT_AUTHOR_EMAIL": email,
            "GIT_COMMITTER_NAME": name,
            "GIT_COMMITTER_EMAIL": email,
        }
        subprocess.run(
            ["git", "commit", "-q", "-m", message],
            cwd=self.repo, check=True, env=identity, capture_output=True,
        )

    def _script(self, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), *args],
            cwd=self.repo, env=self.env, capture_output=True, text=True,
        )

    def test_canonical_commits_pass(self) -> None:
        self._commit("feat: one", name=CANONICAL_NAME, email=CANONICAL_EMAIL)
        self._commit("feat: two", name="ObliviousOdin", email=CANONICAL_EMAIL)
        result = self._script("--range", "HEAD~1..HEAD")
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_ai_author_fails(self) -> None:
        self._commit("feat: base", name=CANONICAL_NAME, email=CANONICAL_EMAIL)
        self._commit("feat: bad", name="Claude", email="noreply@anthropic.com")
        result = self._script("--range", "HEAD~1..HEAD")
        self.assertEqual(result.returncode, 1)
        self.assertIn("AI-tool identity", result.stderr)

    def test_unknown_email_fails(self) -> None:
        self._commit("feat: bad", name="Somebody", email="somebody@example.com")
        result = self._script("--commit", "HEAD")
        self.assertEqual(result.returncode, 1)
        self.assertIn("not an allowlisted repository identity", result.stderr)

    def test_zero_sha_range_audits_head_only(self) -> None:
        self._commit("feat: bad", name="Claude", email="noreply@anthropic.com")
        self._commit("feat: good", name=CANONICAL_NAME, email=CANONICAL_EMAIL)
        result = self._script("--range", "0" * 40 + "..HEAD")
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_message_file_strips_comments(self) -> None:
        message = self.repo / "MSG"
        message.write_text(
            "fix: clean\n\n# Co-Authored-By: Claude <noreply@anthropic.com>\n",
            encoding="utf-8",
        )
        result = self._script("--message-file", str(message))
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_check_config_rejects_ai_identity(self) -> None:
        self._git("config", "--local", "user.name", "Claude")
        self._git("config", "--local", "user.email", "noreply@anthropic.com")
        result = self._script("--check-config")
        self.assertEqual(result.returncode, 1)

    def test_check_config_accepts_canonical_identity(self) -> None:
        self._git("config", "--local", "user.name", CANONICAL_NAME)
        self._git("config", "--local", "user.email", CANONICAL_EMAIL)
        result = self._script("--check-config")
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_check_config_rejects_env_identity_override(self) -> None:
        # Codex review finding: GIT_AUTHOR_* (and --author, which git exports
        # to hooks) must not slip past a config-only check.
        self._git("config", "--local", "user.name", CANONICAL_NAME)
        self._git("config", "--local", "user.email", CANONICAL_EMAIL)
        self.env["GIT_AUTHOR_NAME"] = "Claude"
        self.env["GIT_AUTHOR_EMAIL"] = "noreply@anthropic.com"
        try:
            result = self._script("--check-config")
        finally:
            del self.env["GIT_AUTHOR_NAME"], self.env["GIT_AUTHOR_EMAIL"]
        self.assertEqual(result.returncode, 1)
        self.assertIn("pending author", result.stderr)

    def test_check_config_labels_pending_committer_violations(self) -> None:
        self._git("config", "--local", "user.name", CANONICAL_NAME)
        self._git("config", "--local", "user.email", CANONICAL_EMAIL)
        self.env["GIT_COMMITTER_NAME"] = "Codex"
        self.env["GIT_COMMITTER_EMAIL"] = "codex@openai.com"
        try:
            result = self._script("--check-config")
        finally:
            del self.env["GIT_COMMITTER_NAME"], self.env["GIT_COMMITTER_EMAIL"]
        self.assertEqual(result.returncode, 1)
        self.assertIn("committer Codex", result.stderr)
        self.assertIn("pending committer", result.stderr)

    def test_check_config_rejects_local_web_flow_committer(self) -> None:
        # The web-flow identity only signs server-side merges; a LOCAL
        # pending committer claiming it is deliberately rejected.
        self._git("config", "--local", "user.name", CANONICAL_NAME)
        self._git("config", "--local", "user.email", CANONICAL_EMAIL)
        self.env["GIT_COMMITTER_NAME"] = "GitHub"
        self.env["GIT_COMMITTER_EMAIL"] = "noreply@github.com"
        try:
            result = self._script("--check-config")
        finally:
            del self.env["GIT_COMMITTER_NAME"], self.env["GIT_COMMITTER_EMAIL"]
        self.assertEqual(result.returncode, 1)
        self.assertIn("pending committer", result.stderr)

    def test_pre_push_audits_outgoing_commits(self) -> None:
        self._commit("feat: base", name=CANONICAL_NAME, email=CANONICAL_EMAIL)
        base = self._rev_parse("HEAD")
        self._commit("feat: bad", name="Claude", email="noreply@anthropic.com")
        head = self._rev_parse("HEAD")
        line = f"refs/heads/task {head} refs/heads/task {base}\n"
        result = self._script_stdin("--pre-push", stdin=line)
        self.assertEqual(result.returncode, 1)
        self.assertIn("AI-tool identity", result.stderr)

    def test_pre_push_skips_ref_deletion_and_passes_clean_range(self) -> None:
        self._commit("feat: base", name=CANONICAL_NAME, email=CANONICAL_EMAIL)
        base = self._rev_parse("HEAD")
        self._commit("feat: good", name=CANONICAL_NAME, email=CANONICAL_EMAIL)
        head = self._rev_parse("HEAD")
        lines = (
            f"refs/heads/gone {'0' * 40} refs/heads/gone {head}\n"
            f"refs/heads/task {head} refs/heads/task {base}\n"
        )
        result = self._script_stdin("--pre-push", stdin=lines)
        self.assertEqual(result.returncode, 0, result.stderr)

    def _rev_parse(self, rev: str) -> str:
        return subprocess.run(
            ["git", "rev-parse", rev],
            cwd=self.repo, check=True, env=self.env,
            capture_output=True, text=True,
        ).stdout.strip()

    def _script_stdin(self, *args: str, stdin: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), *args],
            cwd=self.repo, env=self.env, capture_output=True, text=True,
            input=stdin,
        )


class HookWiringTests(unittest.TestCase):
    """The committed hooks and bootstrap must stay wired to the audit."""

    def test_hooks_exist_and_call_the_audit(self) -> None:
        for hook in ("pre-commit", "commit-msg", "pre-push"):
            path = ROOT / ".githooks" / hook
            self.assertTrue(path.is_file(), hook)
            self.assertTrue(os.access(path, os.X_OK), f"{hook} must be executable")
            content = path.read_text(encoding="utf-8")
            self.assertIn("scripts/commit_identity_audit.py", content)

    def test_bootstrap_installs_hookspath_and_identity(self) -> None:
        content = (ROOT / "scripts" / "setup-git-guardrails.sh").read_text(
            encoding="utf-8"
        )
        self.assertIn("core.hooksPath .githooks", content)
        self.assertIn("configure-maintainer-git-identity.py", content)
        self.assertIn("--check-config", content)


if __name__ == "__main__":
    unittest.main()
